### ISSUE TITLE
Collection support

### ISSUE THREAD

**Issue by Kikobeats** [dagthomas/hexSorter#2]
Hello!

I consider this library very useful, thanks for that ❤️ 

After review example, I implemented a loop in my code for sort an input array of colors: https://github.com/microlinkhq/splashy/blob/master/test/index.js#L10

Maybe could be useful to leverage this functionality as part of the library?

**Comment by dagthomas** [comment]
Hi,

Glad you liked it!
I have been meaning to update it with some better functionality - but have
too much to do irl. Will see if I can implement something this xmas ^^

Thanks for your support!

- Dag

Den tir. 11. des. 2018 kl. 11:54 skrev Kiko Beats <notifications@github.com
